#!/bin/bash
# Script to help update logos from local machine

echo "=== T0kenRent Logo Update Helper ==="
echo ""
echo "This script will help you update the logos."
echo ""
echo "Run these commands from your LOCAL machine:"
echo ""
echo "cd /Users/ian/Documents/GitHub/t0kenrent"
echo ""
echo "# Copy files to proper locations (if they have spaces in names)"
echo "cp 'public/wallets/HandCash Logo.png' public/wallets/handcash.png"
echo "cp 'public/wallets/Relysia Logo.png' public/wallets/relysia.png"
echo "cp 'public/t0kenrent logo.png' public/t0kenrent-logo.png"
echo "cp 'public/t0kenrent logo.png' public/favicon.png"
echo ""
echo "# Add to git"
echo "git add public/wallets/handcash.png"
echo "git add public/wallets/relysia.png"
echo "git add public/t0kenrent-logo.png"
echo "git add public/favicon.png"
echo ""
echo "# Commit"
echo 'git commit -m "feat: Update brand logos for HandCash, Relysia, and T0kenRent"'
echo ""
echo "# Push to GitHub"
echo "git push origin main"
echo ""
echo "After pushing, the changes will be pulled into the sandbox automatically!"
